name: "CI/CD"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: banco_olmeca_web_test
          POSTGRES_USER: banco_olmeca
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://banco_olmeca:password@localhost:5432/banco_olmeca_web_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up rails
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bin/bundle install --full-index --jobs 4 --retry 3
      - name: Set up database
        run: |
          bin/bundle exec rails db:create
          bin/bundle exec rails db:migrate
      - name: Run tests
        run: bin/bundle exec rake
